#ifndef _OLDEN_CONFIG_H_
#define _OLDEN_CONFIG_H_

#define OLDEN_BISORT_SIZE 250000
#define OLDEN_BISORT_FLAG 0
#define OLDEN_BISORT_ITER 5

#define OLDEN_MST_LEVEL 1024
#define OLDEN_MST_ITER 5

#define OLDEN_PERIMETER_LEVEL 10
#define OLDEN_PERIMETER_ITER 4

#define OLDEN_TREEADD_LEVEL 21
#define OLDEN_TREEADD_ITER 4

#endif
